services:
  - type: web
    name: last-lite
    env: node
    plan: free
    buildCommand: |
      echo "=== Last-Lite Build Process ==="
      echo "Working directory: $(pwd)"
      echo "Contents:"
      ls -la
      
      echo "=== Building server ==="
      cd server && npm ci && npm run build
      
      echo "=== Building client ==="
      cd ../client && rm -rf node_modules package-lock.json && npm install && npm install @rollup/rollup-linux-x64-gnu --save-optional && npm run build
      
      echo "=== Copying HTML files to dist ==="
      mkdir -p client/dist
      cp client/src/homepage.html client/dist/homepage.html
      cp client/src/polished-game.html client/dist/polished-game.html
      
      echo "=== Build verification ==="
      echo "Client dist contents:"
      ls -la client/dist/
      echo "=== Build complete ==="
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TICK_RATE
        value: 60
      - key: WORLD_BOUNDS
        value: 20
      - key: MAX_ROOM_CCU
        value: 100
    healthCheckPath: /healthz

  - type: pserv
    name: last-lite-db
    plan: free
    env: postgresql
    region: oregon
