services:
  - type: web
    name: last-lite
    env: node
    plan: free
    buildCommand: |
      echo "=== Last-Lite Build Process ==="
      echo "Working directory: $(pwd)"
      echo "Contents:"
      ls -la
      
      echo "=== Using alternative build script ==="
      node build-alternative.js
      
      echo "=== Build verification ==="
      echo "Final structure:"
      ls -la
      echo "Server dist:"
      ls -la server/dist/
      echo "Client dist:"
      ls -la client/dist/
      echo "=== Build complete ==="
    startCommand: cd server && node dist/socket-main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TICK_RATE
        value: 60
      - key: WORLD_BOUNDS
        value: 20
      - key: MAX_ROOM_CCU
        value: 100
    healthCheckPath: /healthz

  - type: pserv
    name: last-lite-db
    plan: free
    env: postgresql
    region: oregon
