services:
  - type: web
    name: last-lite
    env: node
    plan: free
    buildCommand: |
      echo "=== Last-Lite Build Process ==="
      echo "Working directory: $(pwd)"
      echo "Contents:"
      ls -la
      
      echo "=== Installing dependencies ==="
      npm install
      
      echo "=== Building server ==="
      cd src/server
      rm -rf node_modules package-lock.json
      npm install
      npm run build
      echo "Server build complete. Contents:"
      ls -la dist/
      cd ../..
      
      echo "=== Building client ==="
      cd src/client  
      rm -rf node_modules package-lock.json
      npm install
      npm run build
      echo "Client build complete. Contents:"
      ls -la dist/
      cd ../..
      
      echo "=== Build verification ==="
      echo "Final structure:"
      ls -la
      echo "Server dist:"
      ls -la src/server/dist/
      echo "Client dist:"
      ls -la src/client/dist/
      echo "=== Build complete ==="
    startCommand: cd src/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TICK_RATE
        value: 60
      - key: WORLD_BOUNDS
        value: 20
      - key: MAX_ROOM_CCU
        value: 100
    healthCheckPath: /healthz
